name: Test commit
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_GITHUB }}
      - name: Sanitize repo slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return 'ghcr.io/${{ github.repository }}'.toLowerCase()
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: .docker/Dockerfile.ci
          tags: ${{ steps.repo_slug.outputs.result}}/ci:${{github.sha}}
  run-phpunit:
    needs: build-image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    container:
      image: ghcr.io/legion112/discriminator-default-normalizer/ci:${{github.sha}}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_GITHUB }}
      env:
        XDEBUG_MODE: coverage
    steps:
      - name: RUN phpunit
        run: (vendor/bin/phpunit --coverage-php .output/coverage.cov)
      - uses: actions/upload-artifact@v3
        with:
          name: phpunit-coverage-report
          path: .output/coverage.cov

  git-diff:
    needs: run-phpunit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    container:
      image: alpine/git
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - run: (diff HEAD^1 > .output/patch.txt)
      - uses: actions/upload-artifact@v3
        with:
          name: git-diff
          path: .output/patch.txt

  run-coverage-check:
    needs:
      - run-phpunit
      - git-diff
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    container:
      image: fearofcode/phpcov:8
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_GITHUB }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: git-diff
      - uses: actions/download-artifact@v2
        with:
          name: phpunit-coverage-report
      - uses: fearofcode/phpcov:8
        run: (patch-coverage --path-prefix /app .output/coverage.cov .output/patch.txt)

  run-psalm:
    needs: build-image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    container:
      image: ghcr.io/legion112/discriminator-default-normalizer/ci:${{github.sha}}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_GITHUB }}
      env:
        XDEBUG_MODE: coverage
    steps:
      - name: RUN psalm
        run: (psalm)
